alter table Student drop constraint FK_STUDENT_ADDRESS;
alter table Teacher drop constraint FK_TEACHER_ADDRESS;
drop table Address;
alter table Marks drop constraint FK_MARKS_SUBJECT;
alter table Schedule drop constraint FK_SCHEDULE_SUBJECT;
alter table Teacher_Subject drop constraint FK_TEACHER_SUBJECT_SUBJECT;
alter table Truancy drop constraint FK_TRUANCY_SUBJECT;
drop table Subject;
drop table Truancy;
drop table Marks;
alter table Student drop constraint FK_STUDENT_CLASS;
alter table Student NO INHERIT Person;
drop table Student;
alter table Teacher_Subject drop constraint FK_TEACHER_SUBJECT_TEACHER;
alter table Schedule drop constraint FK_SCHEDULE_TEACHER;
alter table Teacher NO INHERIT Person;
drop table Teacher;
drop table Person;
drop table Teacher_Subject;
alter table Schedule drop constraint FK_SCHEDULE_CLASS;
drop table Class;
alter table Schedule drop constraint FK_SCHEDULE_CLASSROOM;
drop table Classroom;
alter table Schedule drop constraint FK_SCHEDULE_WEEKDAY;
drop table WeekDay;
alter table Schedule drop constraint FK_SCHEDULE_LESSONTIME;
drop table LessonTime;
drop table Schedule;